# fly.toml app configuration file generated for pb-out24-joao-lucas-desafio3-yn4zlw on 2025-03-14T08:18:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pb-out24-joao-lucas-desafio3-yn4zlw'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
